// examples/react-test-app-js/src/App.js
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import {Client} from 'api-delivery-js';

class App extends Component {

  constructor(props) {
    super(props);
    this.state = {
      error: null,
      isLoaded: false,
      project: null
    };
  }
  
  componentDidMount() {
     
    var client = Client.create({
      accessToken: 'xxxxxx',
      projectId: 'website',
      rootUrl: 'https://cms-example.cloud.contensis.com'
    });
     client.project.get().then(project => {
      this.setState({
        isLoaded: true,
        project: project
      });
     },  
     error => {
      this.setState({
        isLoaded: true,
        error
      });
    });   
  }
  
  render() {
    const { error, isLoaded, project } = this.state;
    if (error) {
      return <div>Error: {error.message}</div>;
    } else if (!isLoaded) {
      return <div>Loading...</div>;
    } else {
      return (      
        <div className="App">
          <header className="App-header">
            <img src={logo} className="App-logo" alt="logo" />
            <p>
              Connected to Contensis project {project.name}
            </p>
            <a
              className="App-link"
              href="https://reactjs.org"
              target="_blank"
              rel="noopener noreferrer"
            >
              Learn React
            </a>
          </header>
        </div>
      );
    }
  }
}

export default App;

// examples/angular-test-app/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { Client } from 'api-delivery-js';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {

  title = 'angular-test-app';
  contensisProjectName = '';

  ngOnInit(): void {
    const client = Client.create({
      accessToken: 'xxxxx',
      projectId: 'website',
      rootUrl: 'https://cms-example.cloud.contensis.com'
    });
    client.project.get().then(project => {
      this.contensisProjectName = project.name;
    });
  }

}
